module.exports = {
  apps: [
    {
      name: 'skylane-api-dev',
      script: 'dist/src/main',
      instance_var: 'INSTANCE_ID',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/skylane?schema=public',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      log_file: './logs/dev/combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/dev/err.log',
      out_file: './logs/dev/out.log',
      log_type: 'json',
    },
    {
      name: 'skylane-api',
      script: 'dist/src/main',
      instance_var: 'INSTANCE_ID',
      instances: 'max',
      exec_mode: 'cluster',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/skylane?schema=public',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/skylane?schema=public',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      log_file: './logs/prod/combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/prod/err.log',
      out_file: './logs/prod/out.log',
      log_type: 'json',
      max_memory_restart: '1G',
    },
  ],
};